"""write docs/definitions.md from the registry.

usage: python -m casedefs.catalog > docs/definitions.md
"""

from __future__ import annotations

from .cli import _compact
from .definition import Composite
from .registry import all_definitions

FAMILIES = {
    "ccdss": "CCDSS (Public Health Agency of Canada)",
    "tonelli": "Tonelli et al. 2015, 30 chronic conditions (Alberta)",
    "quan.charlson": "Quan et al. 2005, Charlson comorbidities",
    "quan.elixhauser": "Quan et al. 2005, Elixhauser comorbidities",
}


def render() -> str:
    defs = list(all_definitions().values())
    lines = [
        "# Definitions",
        "",
        "This file is generated by `python -m casedefs.catalog`. Don't edit it by hand.",
        "",
        f"{len(defs)} definitions. Codes are prefixes: a code also covers every longer code under it.",
        "",
    ]
    for family, title in FAMILIES.items():
        members = [d for d in defs if d.id.rsplit(".", 1)[0] == family]
        if not members:
            continue
        lines += [f"## {title}", "", f"{len(members)} definitions. Source: {members[0].source_title}.", ""]
        for d in members:
            lines.append(f"### `{d.id}`")
            lines.append("")
            lines.append(f"**{d.name}**. Ages: {d.age_text()}. Verified: {'yes' if d.verified else 'no'}.")
            lines.append("")
            if isinstance(d, Composite):
                parts = ", ".join(f"`{c if isinstance(c, str) else c.id}`" for c in d.components)
                lines += [f"- Rule: {d.describe()}", f"- Conditions: {parts}"]
            else:
                icd9, icd10 = d.claims_codes
                lines.append(f"- Rule: {d.rule.describe()}")
                if not d.complete:
                    lines.append("- **Not fully implemented.** See the notes.")
                if d.rule.min_hospital or d.rule.min_ambulatory:
                    lines.append(f"- Hospital ICD-9: {_compact(d.icd9)}")
                    lines.append(f"- Hospital ICD-10-CA: {_compact(d.icd10ca)}")
                if d.rule.min_claims and (icd9 != d.icd9 or icd10 != d.icd10ca or not d.rule.min_hospital):
                    lines.append(f"- Claims ICD-9: {_compact(icd9)}")
                    lines.append(f"- Claims ICD-10-CA: {_compact(icd10)}")
                if d.excluded_codes:
                    lines.append(f"- Never counts: {_compact(d.excluded_codes)}")
                for e in d.exclusions:
                    lines.append(f"- Exclusion, {e.name}: {e.description}")
            lines.append(f"- Source: {d.source_location}, <{d.source_url}>")
            if d.notes:
                lines.append(f"- Notes: {d.notes}")
            lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":  # pragma: no cover
    import sys

    sys.stdout.reconfigure(encoding="utf-8")
    print(render(), end="")
